// Publishes a rolling fortnight of puzzles to Postgres: generate each date
// into a scratch directory, publish its rows, repeat. The RPC's date gate
// reveals one day at a time, so the future rows are outage insurance that
// nobody can ask for.
//
// This is what turns "GitHub Actions must be up every morning at 07:15" into
// "GitHub Actions must be up once a fortnight" — the generator stays where
// the compute is comfortable, and the schedule stops being urgent.
//
// Day 0 is generated here too, identically to the files the workflow just
// wrote (same date, same salt), so rows and files can never disagree.
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { easternToday, plusDays as plus, publishDate, publishRounds } from './publishDate.mjs';

const WINDOW_DAYS = 14;

const baseDate = process.env.PUZZLES_DATE || easternToday();

const dir = mkdtempSync(join(tmpdir(), 'anagrimoire-window-'));
try {
  // One day at a time through the routine ops/publish-day.sh also uses, so the
  // nightly window and a day regenerated by hand cannot publish differently.
  for (let offset = 0; offset < WINDOW_DAYS; offset++) {
    for (const line of publishDate(plus(baseDate, offset), dir)) console.log(line);
  }
  // Tournament rounds starting inside the same fortnight, after the dailies so
  // a round that fails cannot cost anybody their daily.
  for (const line of await publishRounds(baseDate, plus(baseDate, WINDOW_DAYS - 1), dir)) {
    console.log(line);
  }
  console.log(`Window published: ${baseDate} through ${plus(baseDate, WINDOW_DAYS - 1)}`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
